name: Run Tests on Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' # Adjust to your target framework
      - name: Restore Dependencies for core tests
        run: dotnet restore Core.Tests/Core.Tests.csproj
      - name: Build
        run: dotnet build Core.Tests/Core.Tests.csproj --configuration Release --no-restore
      - name: Run Core Tests
        run: dotnet test Core.Tests/Core.Tests.csproj --configuration Release --no-build
      - name: Restore Dependencies for autofac tests
        run: dotnet restore Core.Autofac.Tests/Core.Autofac.Tests.csproj
      - name: Build
        run: dotnet build Core.Autofac.Tests/Core.Autofac.Tests.csproj --configuration Release --no-restore
      - name: Run Autofac Tests
        run: dotnet test Core.Autofac.Tests/Core.Autofac.Tests.csproj --configuration Release --no-build